owners = []
nickname = "w0bmSays"
alt_nicks = ["user_", "user__"]
username = "user"
realname = "Test User"
server = "irc.n0xy.net"
port = 6697
password = ""
use_ssl = true
encoding = "UTF-8"
channels = ["#w0bm"]
umodes = "+RB-x"
ping_time = 180
ping_timeout = 10
burst_window_length = 8
max_messages_in_burst = 15